services:
  - type: web
    name: campustrack
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn campustrack.wsgi:application"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
